# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.40.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set npm token
          command: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc'
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Check lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Check build
          command: yarn build
workflows:
  version: 2
  autodeploy:
    jobs:
      - test
