name: Update tasks to pending acceptance on push to master
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  update_clickup_tasks:
    runs-on: ubuntu-latest
    name: Updates tasks added in the changelog to pending acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch clickup tast versioning action
        uses: Sparted/github-actions/actions/clickup-task-versioning@v0.0.9
        with:
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          CLICKUP_TASK_STATUS: 'accepted'
