name: Update tasks to accepted on push to master
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  update_clickup_tasks:
    runs-on: ubuntu-latest
    name: Updates tasks added in the changelog to accepted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch clickup tast versioning action
        uses: Sparted/github-actions/actions/clickup-task-versioning@v1.0.0
        with:
          CLICKUP_TOKEN: ${{ secrets.ACTION_CLICKUP_TOKEN }}
          CLICKUP_TASK_STATUS: 'accepted'
