name: Update tasks to pending acceptance on PR merge to master
on:
  pull_request:
    branches:
      - master
      - main
    types: ['closed']
jobs:
  update_clickup_tasks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Updates tasks added in the changelog to pending acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch clickup tast versioning action
        uses: Sparted/github-actions/actions/clickup-task-versioning@v1.0.0
        with:
          clickup-token: ${{ secrets.ACTION_CLICKUP_TOKEN }}
