name: Update tasks to accepted on release
on:
  workflow_dispatch:
  release:
    branches:
      - master
      - main
jobs:
  update_clickup_tasks:
    runs-on: ubuntu-latest
    name: Updates tasks added in the changelog to accepted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch clickup tast release action
        uses: Sparted/github-actions/actions/clickup-task-release@v1.0.0
        with:
          clickup-token: ${{ secrets.ACTION_CLICKUP_TOKEN }}
