name: Update tasks to pending acceptance on PR merge to master
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
    types: ['closed']
jobs:
  update_clickup_tasks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Updates tasks added in the changelog to pending acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch clickup tast versioning action
        uses: Sparted/github-actions/actions/clickup-task-versioning@v0.0.5
        with:
          clickup-token: pk_32459445_1Y7D60GBN77ZBIU2G0D4JSTMHIISUWGL
